{% set name = "featuretools-tsfresh-primitives" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1ded5b013e314263fee37bc26da42b4b3a54516fbec6e962e5147b6c72f88e35

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - tsfresh >=0.19.0
    - pandas >=1.3.0,<2.0.0
    - featuretools >=1.0.0

test:
  imports:
    - featuretools_tsfresh_primitives
  requires:
    - pytest >=4.4.2
    - pip
    - python {{ python_min }}
  source_files:
    - featuretools_tsfresh_primitives/*
  commands:
    - pytest featuretools_tsfresh_primitives/tests

about:
  home: https://github.com/alteryx/featuretools-tsfresh-primitives
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TSFresh primitives for featuretools
  doc_url: https://github.com/alteryx/featuretools-tsfresh-primitives
  dev_url: https://github.com/alteryx/featuretools-tsfresh-primitives

extra:
  recipe-maintainers:
    - davesque
    - gsheni
    - jeff-hernandez
    - rwedge
    - tamargrey
    - thehomebrewnerd
